### PR TITLE
fix bug

### PR DESCRIPTION
**Pull request by wujunze**
fix bug

### CODE REVIEW

**Comment by tennc** [comment]
no, the shell is pic webshell,you can open with notepad,then you will look shell codes

**Comment by wujunze** [comment]
ok  I see

**Comment by tennc** [comment]
can you see it??  shell code

**Comment by wujunze** [comment]
我明白了    你QQ多少?

**Comment by tennc** [comment]
qq 不加人

**Comment by wujunze** [comment]
好吧

**Pull request closed without merging**
